package com.x.lasergrbl_mobile.core

data class BoundaryPreviewSettings(
    val feedRate: Int = 1200,
    val paddingMm: Double = 0.0,
) {
    init {
        require(feedRate in 10..20_000) { "边界预跑进给必须在 10..20000" }
        require(paddingMm >= 0.0) { "边界预跑外扩距离不能为负数" }
    }
}

object BoundaryPreviewPlanner {
    fun plan(bounds: GcodeBounds, settings: BoundaryPreviewSettings = BoundaryPreviewSettings()): List<GcodeLine> {
        require(bounds.hasMotion) { "任务没有可用运动范围" }
        require(bounds.width > 0.0 && bounds.height > 0.0) { "任务 XY 边界尺寸过小，无法生成边界框" }

        val minX = bounds.minX - settings.paddingMm
        val maxX = bounds.maxX + settings.paddingMm
        val minY = bounds.minY - settings.paddingMm
        val maxY = bounds.maxY + settings.paddingMm
        val feed = settings.feedRate

        val commands = listOf(
            "(Boundary preview generated by LaserGRBL Mobile)",
            "M5",
            "G21",
            "G90",
            "G1 X${fmt(minX)} Y${fmt(minY)} F$feed",
            "G1 X${fmt(maxX)} Y${fmt(minY)} F$feed",
            "G1 X${fmt(maxX)} Y${fmt(maxY)} F$feed",
            "G1 X${fmt(minX)} Y${fmt(maxY)} F$feed",
            "G1 X${fmt(minX)} Y${fmt(minY)} F$feed",
            "M5",
        )

        return commands.mapIndexed { index, command ->
            GcodeLine(
                number = index + 1,
                raw = command,
                command = command,
                byteLength = command.toByteArray(Charsets.US_ASCII).size + 1,
            )
        }
    }

    private fun fmt(value: Double): String = "%.3f".format(value)
}
