package com.x.lasergrbl_mobile.core

import kotlin.math.roundToInt
import kotlin.math.pow

enum class ImageDitherMode {
    None, Ordered, FloydSteinberg
}

enum class ImageScanDirection {
    Horizontal, Vertical
}

enum class ImageMaterialPreset(
    val label: String,
    val lineStepMm: Double,
    val feedRate: Int,
    val travelRate: Int,
    val maxPower: Int,
    val burnThreshold: Int,
    val gamma: Double,
    val ditherMode: ImageDitherMode,
) {
    Custom("自定义", 0.12, 1200, 3000, 350, 18, 1.0, ImageDitherMode.None),
    Basswood("椴木", 0.10, 1200, 3000, 380, 16, 1.0, ImageDitherMode.None),
    Cardboard("纸板", 0.14, 1600, 3200, 260, 20, 1.0, ImageDitherMode.Ordered),
    Leather("皮革", 0.12, 1000, 2800, 320, 18, 1.15, ImageDitherMode.Ordered),
    AnodizedAluminum("阳极铝", 0.08, 1800, 3500, 300, 10, 0.85, ImageDitherMode.None),
}

data class GrayRaster(
    val width: Int,
    val height: Int,
    val pixels: IntArray,
) {
    init {
        require(width > 0) { "图片宽度必须大于 0" }
        require(height > 0) { "图片高度必须大于 0" }
        require(pixels.size == width * height) { "灰度像素数量与尺寸不匹配" }
        require(pixels.all { it in 0..255 }) { "灰度值必须在 0..255" }
    }

    fun grayAt(x: Int, y: Int): Int = pixels[y * width + x]
}

data class ImageGcodeSettings(
    val widthMm: Double = 30.0,
    val lineStepMm: Double = 0.12,
    val feedRate: Int = 1200,
    val travelRate: Int = 3000,
    val maxPower: Int = 350,
    val burnThreshold: Int = 18,
    val gamma: Double = 1.0,
    val ditherMode: ImageDitherMode = ImageDitherMode.None,
    val scanDirection: ImageScanDirection = ImageScanDirection.Horizontal,
    val bidirectional: Boolean = true,
    val invert: Boolean = false,
) {
    init {
        require(widthMm > 0.0) { "图片加工宽度必须大于 0" }
        require(lineStepMm > 0.0) { "扫描行距必须大于 0" }
        require(feedRate > 0) { "雕刻进给必须大于 0" }
        require(travelRate > 0) { "空程进给必须大于 0" }
        require(maxPower in 1..1000) { "最大功率必须在 1..1000" }
        require(burnThreshold in 0..255) { "阈值必须在 0..255" }
        require(gamma in 0.1..5.0) { "Gamma 必须在 0.1..5.0" }
    }
}

data class ImageGcodeResult(
    val lines: List<GcodeLine>,
    val widthMm: Double,
    val heightMm: Double,
    val burnedPixels: Int,
)

object ImageToGcodeConverter {
    fun convert(raster: GrayRaster, settings: ImageGcodeSettings = ImageGcodeSettings()): ImageGcodeResult {
        val pixelSize = settings.widthMm / raster.width.toDouble()
        val rowStride = maxOf(1, (settings.lineStepMm / pixelSize).roundToInt())
        val processed = processRaster(raster, settings)
        val output = mutableListOf<String>()

        output += "(Generated by LaserGRBL Mobile)"
        output += "G21"
        output += "G90"
        output += "M5"
        output += "F${settings.feedRate}"

        val burnedPixels = when (settings.scanDirection) {
            ImageScanDirection.Horizontal -> scanHorizontal(raster, processed, rowStride, pixelSize, settings, output)
            ImageScanDirection.Vertical -> scanVertical(raster, processed, rowStride, pixelSize, settings, output)
        }

        output += "M5"
        output += "G0 X0 Y0 F${settings.travelRate}"

        val lines = output.mapIndexed { index, command ->
            GcodeLine(
                number = index + 1,
                raw = command,
                command = command,
                byteLength = command.toByteArray(Charsets.US_ASCII).size + 1,
            )
        }
        return ImageGcodeResult(
            lines = lines,
            widthMm = settings.widthMm,
            heightMm = (raster.height - 1).coerceAtLeast(0) * pixelSize,
            burnedPixels = burnedPixels,
        )
    }

    private fun scanHorizontal(
        raster: GrayRaster,
        powers: IntArray,
        rowStride: Int,
        pixelSize: Double,
        settings: ImageGcodeSettings,
        output: MutableList<String>,
    ): Int {
        var scanIndex = 0
        var burned = 0
        for (sourceY in 0 until raster.height step rowStride) {
            val yMm = sourceY * pixelSize
            val leftToRight = !settings.bidirectional || scanIndex % 2 == 0
            val xRange = if (leftToRight) 0 until raster.width else raster.width - 1 downTo 0
            burned += emitScanLine(xRange, { x -> x * pixelSize }, { yMm }, { x -> powers[sourceY * raster.width + x] }, settings, output)
            scanIndex += 1
        }
        return burned
    }

    private fun scanVertical(
        raster: GrayRaster,
        powers: IntArray,
        colStride: Int,
        pixelSize: Double,
        settings: ImageGcodeSettings,
        output: MutableList<String>,
    ): Int {
        var scanIndex = 0
        var burned = 0
        for (sourceX in 0 until raster.width step colStride) {
            val xMm = sourceX * pixelSize
            val topToBottom = !settings.bidirectional || scanIndex % 2 == 0
            val yRange = if (topToBottom) 0 until raster.height else raster.height - 1 downTo 0
            burned += emitScanLine(yRange, { xMm }, { y -> y * pixelSize }, { y -> powers[y * raster.width + sourceX] }, settings, output)
            scanIndex += 1
        }
        return burned
    }

    private fun emitScanLine(
        range: IntProgression,
        xFor: (Int) -> Double,
        yFor: (Int) -> Double,
        powerFor: (Int) -> Int,
        settings: ImageGcodeSettings,
        output: MutableList<String>,
    ): Int {
        var laserOn = false
        var burned = 0
        for (index in range) {
            val power = powerFor(index)
            if (power <= 0) {
                if (laserOn) {
                    output += "M5"
                    laserOn = false
                }
                continue
            }

            val xMm = xFor(index)
            val yMm = yFor(index)
            if (!laserOn) {
                output += "G0 X${fmt(xMm)} Y${fmt(yMm)} F${settings.travelRate}"
                output += "M4 S$power"
                laserOn = true
            }
            burned += 1
            output += "G1 X${fmt(xMm)} Y${fmt(yMm)} S$power F${settings.feedRate}"
        }

        if (laserOn) {
            output += "M5"
        }
        return burned
    }

    private fun processRaster(raster: GrayRaster, settings: ImageGcodeSettings): IntArray {
        val levels = DoubleArray(raster.width * raster.height) { index ->
            val gray = raster.pixels[index]
            val darkness = if (settings.invert) gray else 255 - gray
            val normalized = (darkness / 255.0).coerceIn(0.0, 1.0).pow(settings.gamma)
            if (normalized * 255.0 < settings.burnThreshold) 0.0 else normalized
        }

        return when (settings.ditherMode) {
            ImageDitherMode.None -> levels.toPowerArray(settings.maxPower)
            ImageDitherMode.Ordered -> orderedDither(levels, raster.width, settings.maxPower)
            ImageDitherMode.FloydSteinberg -> floydSteinbergDither(levels, raster.width, raster.height, settings.maxPower)
        }
    }

    private fun DoubleArray.toPowerArray(maxPower: Int): IntArray {
        return IntArray(size) { index ->
            val value = this[index]
            if (value <= 0.0) 0 else (value * maxPower).roundToInt().coerceIn(1, maxPower)
        }
    }

    private fun orderedDither(levels: DoubleArray, width: Int, maxPower: Int): IntArray {
        val bayer = intArrayOf(
            0, 8, 2, 10,
            12, 4, 14, 6,
            3, 11, 1, 9,
            15, 7, 13, 5,
        )
        return IntArray(levels.size) { index ->
            val x = index % width
            val y = index / width
            val threshold = (bayer[(y % 4) * 4 + (x % 4)] + 0.5) / 16.0
            if (levels[index] > threshold) maxPower else 0
        }
    }

    private fun floydSteinbergDither(levels: DoubleArray, width: Int, height: Int, maxPower: Int): IntArray {
        val work = levels.copyOf()
        val out = IntArray(work.size)
        fun add(x: Int, y: Int, error: Double, factor: Double) {
            if (x in 0 until width && y in 0 until height) {
                val idx = y * width + x
                work[idx] = (work[idx] + error * factor).coerceIn(0.0, 1.0)
            }
        }

        for (y in 0 until height) {
            for (x in 0 until width) {
                val index = y * width + x
                val oldValue = work[index]
                val newValue = if (oldValue >= 0.5) 1.0 else 0.0
                out[index] = if (newValue > 0.0) maxPower else 0
                val error = oldValue - newValue
                add(x + 1, y, error, 7.0 / 16.0)
                add(x - 1, y + 1, error, 3.0 / 16.0)
                add(x, y + 1, error, 5.0 / 16.0)
                add(x + 1, y + 1, error, 1.0 / 16.0)
            }
        }
        return out
    }

    private fun fmt(value: Double): String = "%.3f".format(value)
}
