package com.x.lasergrbl_mobile.core

import kotlin.math.roundToInt

data class GrayRaster(
    val width: Int,
    val height: Int,
    val pixels: IntArray,
) {
    init {
        require(width > 0) { "图片宽度必须大于 0" }
        require(height > 0) { "图片高度必须大于 0" }
        require(pixels.size == width * height) { "灰度像素数量与尺寸不匹配" }
        require(pixels.all { it in 0..255 }) { "灰度值必须在 0..255" }
    }

    fun grayAt(x: Int, y: Int): Int = pixels[y * width + x]
}

data class ImageGcodeSettings(
    val widthMm: Double = 30.0,
    val lineStepMm: Double = 0.12,
    val feedRate: Int = 1200,
    val travelRate: Int = 3000,
    val maxPower: Int = 350,
    val burnThreshold: Int = 18,
    val bidirectional: Boolean = true,
    val invert: Boolean = false,
) {
    init {
        require(widthMm > 0.0) { "图片加工宽度必须大于 0" }
        require(lineStepMm > 0.0) { "扫描行距必须大于 0" }
        require(feedRate > 0) { "雕刻进给必须大于 0" }
        require(travelRate > 0) { "空程进给必须大于 0" }
        require(maxPower in 1..1000) { "最大功率必须在 1..1000" }
        require(burnThreshold in 0..255) { "阈值必须在 0..255" }
    }
}

data class ImageGcodeResult(
    val lines: List<GcodeLine>,
    val widthMm: Double,
    val heightMm: Double,
    val burnedPixels: Int,
)

object ImageToGcodeConverter {
    fun convert(raster: GrayRaster, settings: ImageGcodeSettings = ImageGcodeSettings()): ImageGcodeResult {
        val pixelSize = settings.widthMm / raster.width.toDouble()
        val rowStride = maxOf(1, (settings.lineStepMm / pixelSize).roundToInt())
        val output = mutableListOf<String>()
        var burnedPixels = 0

        output += "(Generated by LaserGRBL Mobile)"
        output += "G21"
        output += "G90"
        output += "M5"
        output += "F${settings.feedRate}"

        var rowIndex = 0
        for (sourceY in 0 until raster.height step rowStride) {
            val yMm = rowIndex * settings.lineStepMm
            val leftToRight = !settings.bidirectional || rowIndex % 2 == 0
            val xRange = if (leftToRight) 0 until raster.width else raster.width - 1 downTo 0
            var laserOn = false

            for (x in xRange) {
                val power = powerFor(raster.grayAt(x, sourceY), settings)
                val xMm = x * pixelSize
                if (power <= 0) {
                    if (laserOn) {
                        output += "M5"
                        laserOn = false
                    }
                    continue
                }

                burnedPixels += 1
                if (!laserOn) {
                    output += "G0 X${fmt(xMm)} Y${fmt(yMm)} F${settings.travelRate}"
                    output += "M4 S$power"
                    laserOn = true
                }
                output += "G1 X${fmt(xMm)} Y${fmt(yMm)} S$power F${settings.feedRate}"
            }

            if (laserOn) {
                output += "M5"
            }
            rowIndex += 1
        }

        output += "M5"
        output += "G0 X0 Y0 F${settings.travelRate}"

        val lines = output.mapIndexed { index, command ->
            GcodeLine(
                number = index + 1,
                raw = command,
                command = command,
                byteLength = command.toByteArray(Charsets.US_ASCII).size + 1,
            )
        }
        return ImageGcodeResult(
            lines = lines,
            widthMm = settings.widthMm,
            heightMm = (rowIndex - 1).coerceAtLeast(0) * settings.lineStepMm,
            burnedPixels = burnedPixels,
        )
    }

    private fun powerFor(gray: Int, settings: ImageGcodeSettings): Int {
        val darkness = if (settings.invert) gray else 255 - gray
        if (darkness < settings.burnThreshold) return 0
        val normalized = darkness / 255.0
        return (normalized * settings.maxPower).roundToInt().coerceIn(1, settings.maxPower)
    }

    private fun fmt(value: Double): String = "%.3f".format(value)
}
