package com.x.lasergrbl_mobile.core

import kotlin.math.max
import kotlin.math.roundToInt

data class SvgGcodeSettings(
    val widthMm: Double = 30.0,
    val feedRate: Int = 1000,
    val travelRate: Int = 3000,
    val power: Int = 250,
) {
    init {
        require(widthMm > 0.0) { "SVG 加工宽度必须大于 0" }
        require(feedRate > 0) { "雕刻进给必须大于 0" }
        require(travelRate > 0) { "空程进给必须大于 0" }
        require(power in 1..1000) { "功率必须在 1..1000" }
    }
}

data class SvgGcodeResult(
    val lines: List<GcodeLine>,
    val pathCount: Int,
    val segmentCount: Int,
    val unsupportedCommands: Set<Char>,
)

object SvgToGcodeConverter {
    private val pathRegex = Regex("""<path\b[^>]*\bd\s*=\s*["']([^"']+)["']""", RegexOption.IGNORE_CASE)

    fun convert(svg: String, settings: SvgGcodeSettings = SvgGcodeSettings()): SvgGcodeResult {
        val parsedPaths = pathRegex.findAll(svg)
            .mapNotNull { parsePath(it.groupValues[1]) }
            .toList()
        if (parsedPaths.isEmpty()) {
            error("未找到可转换的 SVG path")
        }

        val allPoints = parsedPaths.flatMap { it.segments.flatMap { segment -> listOf(segment.start, segment.end) } }
        if (allPoints.isEmpty()) {
            error("SVG path 中没有可转换的线段")
        }
        val minX = allPoints.minOf { it.x }
        val maxX = allPoints.maxOf { it.x }
        val minY = allPoints.minOf { it.y }
        val maxY = allPoints.maxOf { it.y }
        val sourceWidth = max(0.0001, maxX - minX)
        val scale = settings.widthMm / sourceWidth
        val output = mutableListOf<String>()

        output += "(Generated by LaserGRBL Mobile SVG)"
        output += "G21"
        output += "G90"
        output += "M5"

        parsedPaths.forEach { path ->
            path.segments.forEachIndexed { index, segment ->
                val start = segment.start.toMachine(minX, minY, maxY, scale)
                val end = segment.end.toMachine(minX, minY, maxY, scale)
                if (index == 0 || !segment.continuesFromPrevious) {
                    output += "M5"
                    output += "G0 X${fmt(start.x)} Y${fmt(start.y)} F${settings.travelRate}"
                    output += "M4 S${settings.power}"
                }
                output += "G1 X${fmt(end.x)} Y${fmt(end.y)} S${settings.power} F${settings.feedRate}"
            }
            output += "M5"
        }
        output += "M5"
        output += "G0 X0 Y0 F${settings.travelRate}"

        val lines = output.mapIndexed { index, command ->
            GcodeLine(
                number = index + 1,
                raw = command,
                command = command,
                byteLength = command.toByteArray(Charsets.US_ASCII).size + 1,
            )
        }
        return SvgGcodeResult(
            lines = lines,
            pathCount = parsedPaths.size,
            segmentCount = parsedPaths.sumOf { it.segments.size },
            unsupportedCommands = parsedPaths.flatMap { it.unsupportedCommands }.toSet(),
        )
    }

    private fun parsePath(data: String): ParsedPath? {
        val tokens = tokenizePath(data)
        var index = 0
        var command: Char? = null
        var current = SvgPoint(0.0, 0.0)
        var subPathStart = current
        var startsNewSubPath = true
        val segments = mutableListOf<SvgSegment>()
        val unsupported = mutableSetOf<Char>()

        fun hasNumber(): Boolean = index < tokens.size && tokens[index].toDoubleOrNull() != null
        fun number(): Double = tokens[index++].toDouble()
        fun nextCommandOrNull(): Char? {
            if (index >= tokens.size) return null
            val token = tokens[index]
            return if (token.length == 1 && token[0].isLetter()) token[0] else null
        }

        while (index < tokens.size) {
            nextCommandOrNull()?.let {
                command = it
                index += 1
            }
            val cmd = command ?: break
            val relative = cmd.isLowerCase()
            when (cmd.uppercaseChar()) {
                'M' -> {
                    if (!hasNumber()) break
                    val first = point(number(), number(), current, relative)
                    current = first
                    subPathStart = first
                    startsNewSubPath = true
                    while (hasNumber()) {
                        val next = point(number(), number(), current, relative)
                        segments += SvgSegment(current, next, continuesFromPrevious = !startsNewSubPath)
                        current = next
                        startsNewSubPath = false
                    }
                }
                'L' -> {
                    while (hasNumber()) {
                        val next = point(number(), number(), current, relative)
                        segments += SvgSegment(current, next, continuesFromPrevious = !startsNewSubPath)
                        current = next
                        startsNewSubPath = false
                    }
                }
                'H' -> {
                    while (hasNumber()) {
                        val x = number()
                        val next = current.copy(x = if (relative) current.x + x else x)
                        segments += SvgSegment(current, next, continuesFromPrevious = !startsNewSubPath)
                        current = next
                        startsNewSubPath = false
                    }
                }
                'V' -> {
                    while (hasNumber()) {
                        val y = number()
                        val next = current.copy(y = if (relative) current.y + y else y)
                        segments += SvgSegment(current, next, continuesFromPrevious = !startsNewSubPath)
                        current = next
                        startsNewSubPath = false
                    }
                }
                'Z' -> {
                    if (current != subPathStart) {
                        segments += SvgSegment(current, subPathStart, continuesFromPrevious = true)
                        current = subPathStart
                    }
                    startsNewSubPath = true
                    command = null
                }
                else -> {
                    unsupported += cmd.uppercaseChar()
                    while (index < tokens.size && nextCommandOrNull() == null) {
                        index += 1
                    }
                }
            }
        }

        return if (segments.isEmpty() && unsupported.isEmpty()) null else ParsedPath(segments, unsupported)
    }

    private fun tokenizePath(data: String): List<String> {
        val tokens = mutableListOf<String>()
        var i = 0
        while (i < data.length) {
            val ch = data[i]
            when {
                ch.isWhitespace() || ch == ',' -> i += 1
                ch.isLetter() -> {
                    tokens += ch.toString()
                    i += 1
                }
                else -> {
                    val start = i
                    i += 1
                    while (i < data.length) {
                        val c = data[i]
                        val previous = data[i - 1]
                        val signStartsNumber = (c == '-' || c == '+') && previous != 'e' && previous != 'E'
                        if (c.isWhitespace() || c == ',' || c.isLetter() || signStartsNumber) break
                        i += 1
                    }
                    tokens += data.substring(start, i)
                }
            }
        }
        return tokens
    }

    private fun point(x: Double, y: Double, current: SvgPoint, relative: Boolean): SvgPoint {
        return if (relative) SvgPoint(current.x + x, current.y + y) else SvgPoint(x, y)
    }

    private fun SvgPoint.toMachine(minX: Double, minY: Double, maxY: Double, scale: Double): SvgPoint {
        return SvgPoint(
            x = (x - minX) * scale,
            y = (maxY - y) * scale,
        )
    }

    private fun fmt(value: Double): String = "%.3f".format(value.roundTo(0.001))

    private fun Double.roundTo(step: Double): Double = (this / step).roundToInt() * step
}

private data class SvgPoint(val x: Double, val y: Double)

private data class SvgSegment(
    val start: SvgPoint,
    val end: SvgPoint,
    val continuesFromPrevious: Boolean,
)

private data class ParsedPath(
    val segments: List<SvgSegment>,
    val unsupportedCommands: Set<Char>,
)
