package com.x.lasergrbl_mobile.core

import java.io.StringReader
import java.util.Locale
import javax.xml.parsers.DocumentBuilderFactory
import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.atan2
import kotlin.math.ceil
import kotlin.math.cos
import kotlin.math.hypot
import kotlin.math.max
import kotlin.math.roundToInt
import kotlin.math.sin
import kotlin.math.sqrt
import kotlin.math.tan
import org.w3c.dom.Element
import org.w3c.dom.Node
import org.xml.sax.InputSource

data class SvgGcodeSettings(
    val widthMm: Double = 30.0,
    val feedRate: Int = 1000,
    val travelRate: Int = 3000,
    val power: Int = 250,
    val colorLayering: Boolean = true,
    val layerOverrides: List<SvgLayerOverride> = emptyList(),
) {
    init {
        require(widthMm > 0.0) { "SVG 加工宽度必须大于 0" }
        require(feedRate > 0) { "雕刻进给必须大于 0" }
        require(travelRate > 0) { "空程进给必须大于 0" }
        require(power in 1..1000) { "功率必须在 1..1000" }
        layerOverrides.forEach { override ->
            require(override.power in 1..1000) { "SVG 图层功率必须在 1..1000" }
            require(override.feedRate in 10..20_000) { "SVG 图层进给必须在 10..20000" }
        }
    }
}

enum class SvgLayerTarget(val label: String) {
    Default("默认/黑"),
    Red("红"),
    Blue("蓝"),
    Green("绿"),
    YellowOrange("黄/橙"),
    Other("其他"),
}

data class SvgLayerOverride(
    val target: SvgLayerTarget,
    val enabled: Boolean = true,
    val power: Int,
    val feedRate: Int,
)

data class SvgGcodeResult(
    val lines: List<GcodeLine>,
    val pathCount: Int,
    val segmentCount: Int,
    val unsupportedCommands: Set<Char>,
    val layerCount: Int,
    val layers: List<SvgLayerSummary>,
)

data class SvgLayerSummary(
    val label: String,
    val target: SvgLayerTarget,
    val pathCount: Int,
    val segmentCount: Int,
    val power: Int,
    val feedRate: Int,
)

object SvgToGcodeConverter {
    private const val CurveFlatness = 0.6
    private const val MaxCurveDepth = 10
    private val transformRegex = Regex("""([a-zA-Z]+)\s*\(([^)]*)\)""")
    private val numberRegex = Regex("""[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?""")

    fun convert(svg: String, settings: SvgGcodeSettings = SvgGcodeSettings()): SvgGcodeResult {
        val parsedPaths = parseSvg(svg)
        if (parsedPaths.isEmpty()) {
            error("未找到可转换的 SVG 图形")
        }
        val outputLayers = buildOutputLayers(parsedPaths, settings)
        val activePaths = outputLayers.flatMap { it.paths }
        if (activePaths.isEmpty()) {
            error("SVG 图层均已跳过，没有可转换的线段")
        }

        val allPoints = activePaths.flatMap { it.segments.flatMap { segment -> listOf(segment.start, segment.end) } }
        if (allPoints.isEmpty()) {
            error("SVG 图形中没有可转换的线段")
        }
        val minX = allPoints.minOf { it.x }
        val maxX = allPoints.maxOf { it.x }
        val minY = allPoints.minOf { it.y }
        val maxY = allPoints.maxOf { it.y }
        val sourceWidth = max(0.0001, maxX - minX)
        val scale = settings.widthMm / sourceWidth
        val output = mutableListOf<String>()

        output += "(Generated by LaserGRBL Mobile SVG)"
        output += "G21"
        output += "G90"
        output += "M5"
        output += "(SVG layers ${outputLayers.size})"

        outputLayers.forEach { layer ->
            output += "(SVG layer ${layer.profile.label} S${layer.profile.power} F${layer.profile.feedRate} paths ${layer.paths.size})"
            layer.paths.forEach { path ->
                path.segments.forEachIndexed { index, segment ->
                    val start = segment.start.toMachine(minX, maxY, scale)
                    val end = segment.end.toMachine(minX, maxY, scale)
                    if (index == 0 || !segment.continuesFromPrevious) {
                        output += "M5"
                        output += "G0 X${fmt(start.x)} Y${fmt(start.y)} F${settings.travelRate}"
                        output += "M4 S${layer.profile.power}"
                    }
                    output += "G1 X${fmt(end.x)} Y${fmt(end.y)} S${layer.profile.power} F${layer.profile.feedRate}"
                }
                output += "M5"
            }
        }
        output += "M5"
        output += "G0 X0 Y0 F${settings.travelRate}"

        val lines = output.mapIndexed { index, command ->
            GcodeLine(
                number = index + 1,
                raw = command,
                command = command,
                byteLength = command.toByteArray(Charsets.US_ASCII).size + 1,
            )
        }
        return SvgGcodeResult(
            lines = lines,
            pathCount = activePaths.size,
            segmentCount = activePaths.sumOf { it.segments.size },
            unsupportedCommands = activePaths.flatMap { it.unsupportedCommands }.toSet(),
            layerCount = outputLayers.size,
            layers = outputLayers.map { layer ->
                SvgLayerSummary(
                    label = layer.profile.label,
                    target = layer.profile.target,
                    pathCount = layer.paths.size,
                    segmentCount = layer.paths.sumOf { it.segments.size },
                    power = layer.profile.power,
                    feedRate = layer.profile.feedRate,
                )
            },
        )
    }

    private fun parseSvg(svg: String): List<ParsedPath> {
        val factory = DocumentBuilderFactory.newInstance().apply {
            isNamespaceAware = false
            isIgnoringComments = true
            setFeatureSafely("http://apache.org/xml/features/disallow-doctype-decl", true)
            setFeatureSafely("http://xml.org/sax/features/external-general-entities", false)
            setFeatureSafely("http://xml.org/sax/features/external-parameter-entities", false)
            setFeatureSafely("http://apache.org/xml/features/nonvalidating/load-external-dtd", false)
        }
        val document = factory
            .newDocumentBuilder()
            .parse(InputSource(StringReader(svg)))

        return collectElements(document.documentElement, SvgMatrix.Identity, SvgStyle.Default)
    }

    private fun DocumentBuilderFactory.setFeatureSafely(feature: String, enabled: Boolean) {
        try {
            setFeature(feature, enabled)
        } catch (_: Exception) {
        }
    }

    private fun buildOutputLayers(paths: List<ParsedPath>, settings: SvgGcodeSettings): List<SvgOutputLayer> {
        if (!settings.colorLayering) {
            return listOf(
                SvgOutputLayer(
                    profile = SvgLayerProfile("single", SvgLayerTarget.Default, settings.power, settings.feedRate),
                    paths = paths,
                )
            )
        }

        val ordered = linkedMapOf<SvgLayerKey, MutableList<ParsedPath>>()
        paths.forEach { path ->
            ordered.getOrPut(path.layer) { mutableListOf() } += path
        }
        return ordered.mapNotNull { (layer, layerPaths) ->
            val profile = layerProfile(layer, settings) ?: return@mapNotNull null
            SvgOutputLayer(profile = profile, paths = layerPaths)
        }
    }

    private fun layerProfile(layer: SvgLayerKey, settings: SvgGcodeSettings): SvgLayerProfile? {
        val target = layerTarget(layer)
        val override = settings.layerOverrides.firstOrNull { it.target == target }
        if (override != null) {
            if (!override.enabled) return null
            return SvgLayerProfile(layer.label, target, override.power, override.feedRate)
        }

        val rgb = rgbFromHex(layer.id)
        if (rgb == null) {
            return SvgLayerProfile(layer.label, target, settings.power, settings.feedRate)
        }
        if (layer.id == SvgLayerKey.Default.id) {
            return SvgLayerProfile(layer.label, target, settings.power, settings.feedRate)
        }

        val (r, g, b) = rgb
        val luma = r * 0.299 + g * 0.587 + b * 0.114
        val darkness = (1.0 - luma / 255.0).coerceIn(0.0, 1.0)
        val (powerMultiplier, feedMultiplier) = when {
            r >= 180 && g <= 120 && b <= 120 -> 1.00 to 0.75
            b >= 160 && r <= 140 && g <= 180 -> 0.55 to 1.25
            g >= 140 && r <= 150 && b <= 150 -> 0.70 to 1.15
            r >= 180 && g >= 130 && b <= 100 -> 0.45 to 1.35
            else -> (0.25 + 0.75 * darkness) to (1.25 - 0.35 * darkness)
        }
        val power = (settings.power * powerMultiplier).roundToInt().coerceIn(1, settings.power.coerceAtLeast(1))
        val feed = (settings.feedRate * feedMultiplier).roundToInt().coerceIn(10, 20_000)
        return SvgLayerProfile(layer.label, target, power, feed)
    }

    private fun layerTarget(layer: SvgLayerKey): SvgLayerTarget {
        if (layer.id == SvgLayerKey.Default.id) return SvgLayerTarget.Default
        val rgb = rgbFromHex(layer.id) ?: return SvgLayerTarget.Other
        val (r, g, b) = rgb
        return when {
            r >= 180 && g <= 120 && b <= 120 -> SvgLayerTarget.Red
            b >= 160 && r <= 140 && g <= 180 -> SvgLayerTarget.Blue
            g >= 140 && r <= 150 && b <= 150 -> SvgLayerTarget.Green
            r >= 180 && g >= 130 && b <= 100 -> SvgLayerTarget.YellowOrange
            else -> SvgLayerTarget.Other
        }
    }

    private fun mergeStyle(parent: SvgStyle, element: Element): SvgStyle {
        val inline = parseStyleMap(element.attr("style"))
        fun property(name: String): String? {
            return element.attr(name).takeIf { it.isNotBlank() } ?: inline[name]
        }

        return parent.copy(
            stroke = property("stroke") ?: parent.stroke,
            fill = property("fill") ?: parent.fill,
            color = property("color") ?: parent.color,
            display = property("display") ?: parent.display,
            visibility = property("visibility") ?: parent.visibility,
            opacity = property("opacity") ?: parent.opacity,
            strokeOpacity = property("stroke-opacity") ?: parent.strokeOpacity,
            fillOpacity = property("fill-opacity") ?: parent.fillOpacity,
        )
    }

    private fun parseStyleMap(value: String): Map<String, String> {
        if (value.isBlank()) return emptyMap()
        return value
            .split(';')
            .mapNotNull { item ->
                val key = item.substringBefore(':').trim().lowercase(Locale.US)
                val raw = item.substringAfter(':', "").trim()
                if (key.isBlank() || raw.isBlank()) null else key to raw
            }
            .toMap()
    }

    private fun SvgStyle.isHidden(): Boolean {
        return display.trim().equals("none", ignoreCase = true) ||
            visibility.trim().lowercase(Locale.US).let { it == "hidden" || it == "collapse" } ||
            opacity.toOpacity() <= 0.0
    }

    private fun SvgStyle.layerKey(): SvgLayerKey? {
        val strokeLayer = visiblePaint(stroke, strokeOpacity, color)
        if (strokeLayer != null) return strokeLayer
        return visiblePaint(fill, fillOpacity, color)
    }

    private fun visiblePaint(value: String?, opacity: String, currentColor: String): SvgLayerKey? {
        if (opacity.toOpacity() <= 0.0) return null
        val normalized = normalizePaint(value ?: return null, currentColor) ?: return null
        return SvgLayerKey(normalized, normalized)
    }

    private fun normalizePaint(value: String, currentColor: String): String? {
        val raw = value.trim().lowercase(Locale.US)
        if (raw.isBlank() || raw == "none" || raw == "transparent") return null
        if (raw == "currentcolor") return normalizePaint(currentColor, SvgStyle.Default.color) ?: SvgLayerKey.Default.id
        if (raw.startsWith("url(")) return "paint"
        if (raw.startsWith("#")) return normalizeHex(raw)
        if (raw.startsWith("rgb")) return normalizeRgbFunction(raw)
        return namedColor(raw)
    }

    private fun normalizeHex(value: String): String? {
        val hex = value.drop(1).takeWhile { it.isDigit() || it.lowercaseChar() in 'a'..'f' }
        return when (hex.length) {
            3 -> "#${hex[0]}${hex[0]}${hex[1]}${hex[1]}${hex[2]}${hex[2]}"
            6 -> "#$hex"
            8 -> if (hex.takeLast(2) == "00") null else "#${hex.take(6)}"
            else -> null
        }
    }

    private fun normalizeRgbFunction(value: String): String? {
        val args = value.substringAfter('(', "").substringBeforeLast(')', "")
            .split(',', ' ')
            .map { it.trim() }
            .filter { it.isNotBlank() }
        if (args.size < 3) return null
        val alpha = args.getOrNull(3)?.toDoubleOrNull()
        if (alpha != null && alpha <= 0.0) return null
        val rgb = args.take(3).map { part ->
            if (part.endsWith("%")) {
                ((part.dropLast(1).toDoubleOrNull() ?: return null) * 2.55).roundToInt()
            } else {
                part.toDoubleOrNull()?.roundToInt() ?: return null
            }.coerceIn(0, 255)
        }
        return "#${rgb.joinToString("") { "%02x".format(it) }}"
    }

    private fun namedColor(value: String): String? {
        return when (value) {
            "black" -> "#000000"
            "white" -> "#ffffff"
            "red" -> "#ff0000"
            "green" -> "#008000"
            "lime" -> "#00ff00"
            "blue" -> "#0000ff"
            "yellow" -> "#ffff00"
            "orange" -> "#ffa500"
            "purple" -> "#800080"
            "magenta", "fuchsia" -> "#ff00ff"
            "cyan", "aqua" -> "#00ffff"
            "gray", "grey" -> "#808080"
            "silver" -> "#c0c0c0"
            "maroon" -> "#800000"
            "navy" -> "#000080"
            "teal" -> "#008080"
            "olive" -> "#808000"
            else -> null
        }
    }

    private fun rgbFromHex(value: String): Triple<Int, Int, Int>? {
        if (!value.startsWith("#") || value.length != 7) return null
        val r = value.substring(1, 3).toIntOrNull(16) ?: return null
        val g = value.substring(3, 5).toIntOrNull(16) ?: return null
        val b = value.substring(5, 7).toIntOrNull(16) ?: return null
        return Triple(r, g, b)
    }

    private fun String.toOpacity(): Double {
        return trim().removeSuffix("%").toDoubleOrNull()?.let { value ->
            if (trim().endsWith("%")) value / 100.0 else value
        }?.coerceIn(0.0, 1.0) ?: 1.0
    }

    private fun collectElements(element: Element, parentTransform: SvgMatrix, parentStyle: SvgStyle): List<ParsedPath> {
        val transform = parentTransform.multiply(parseTransform(element.attr("transform")))
        val style = mergeStyle(parentStyle, element)
        if (style.isHidden()) return emptyList()
        val layer = style.layerKey()
        val tag = element.tagName.substringAfter(':').lowercase(Locale.US)
        val current = if (layer == null) {
            null
        } else when (tag) {
            "path" -> element.attr("d").takeIf { it.isNotBlank() }?.let { parsePath(it, transform) }?.copy(layer = layer)
            "rect" -> parseRect(element, transform)?.copy(layer = layer)
            "circle" -> parseCircle(element, transform)?.copy(layer = layer)
            "ellipse" -> parseEllipse(element, transform)?.copy(layer = layer)
            "polyline" -> parsePolyPoints(element, close = false, transform)?.copy(layer = layer)
            "polygon" -> parsePolyPoints(element, close = true, transform)?.copy(layer = layer)
            else -> null
        }

        val results = mutableListOf<ParsedPath>()
        current?.takeIf { it.segments.isNotEmpty() || it.unsupportedCommands.isNotEmpty() }?.let { results += it }

        val children = element.childNodes
        for (i in 0 until children.length) {
            val child = children.item(i)
            if (child.nodeType == Node.ELEMENT_NODE) {
                results += collectElements(child as Element, transform, style)
            }
        }
        return results
    }

    private fun parseRect(element: Element, transform: SvgMatrix): ParsedPath? {
        val x = element.doubleAttr("x") ?: 0.0
        val y = element.doubleAttr("y") ?: 0.0
        val width = element.doubleAttr("width") ?: return null
        val height = element.doubleAttr("height") ?: return null
        if (width <= 0.0 || height <= 0.0) return null

        return pointsToPath(
            listOf(
                SvgPoint(x, y),
                SvgPoint(x + width, y),
                SvgPoint(x + width, y + height),
                SvgPoint(x, y + height),
            ),
            close = true,
            transform = transform,
        )
    }

    private fun parseCircle(element: Element, transform: SvgMatrix): ParsedPath? {
        val cx = element.doubleAttr("cx") ?: 0.0
        val cy = element.doubleAttr("cy") ?: 0.0
        val r = element.doubleAttr("r") ?: return null
        if (r <= 0.0) return null
        return ovalToPath(cx, cy, r, r, transform)
    }

    private fun parseEllipse(element: Element, transform: SvgMatrix): ParsedPath? {
        val cx = element.doubleAttr("cx") ?: 0.0
        val cy = element.doubleAttr("cy") ?: 0.0
        val rx = element.doubleAttr("rx") ?: return null
        val ry = element.doubleAttr("ry") ?: return null
        if (rx <= 0.0 || ry <= 0.0) return null
        return ovalToPath(cx, cy, rx, ry, transform)
    }

    private fun ovalToPath(cx: Double, cy: Double, rx: Double, ry: Double, transform: SvgMatrix): ParsedPath {
        val radius = max(rx, ry)
        val steps = ceil(2.0 * PI * radius / 3.0).toInt().coerceIn(24, 144)
        val points = (0 until steps).map { index ->
            val angle = 2.0 * PI * index / steps
            SvgPoint(cx + cos(angle) * rx, cy + sin(angle) * ry)
        }
        return pointsToPath(points, close = true, transform = transform) ?: ParsedPath(emptyList(), emptySet())
    }

    private fun parsePolyPoints(element: Element, close: Boolean, transform: SvgMatrix): ParsedPath? {
        val points = numberRegex.findAll(element.attr("points"))
            .mapNotNull { it.value.toDoubleOrNull() }
            .chunked(2)
            .filter { it.size == 2 }
            .map { SvgPoint(it[0], it[1]) }
            .toList()
        return pointsToPath(points, close, transform)
    }

    private fun pointsToPath(points: List<SvgPoint>, close: Boolean, transform: SvgMatrix): ParsedPath? {
        if (points.size < 2) return null
        val transformed = points.map(transform::map)
        val segments = mutableListOf<SvgSegment>()
        for (i in 0 until transformed.lastIndex) {
            segments += SvgSegment(transformed[i], transformed[i + 1], continuesFromPrevious = i > 0)
        }
        if (close && transformed.size > 2 && transformed.last() != transformed.first()) {
            segments += SvgSegment(transformed.last(), transformed.first(), continuesFromPrevious = true)
        }
        return ParsedPath(segments, emptySet())
    }

    private fun parsePath(data: String, transform: SvgMatrix = SvgMatrix.Identity): ParsedPath? {
        val tokens = tokenizePath(data)
        var index = 0
        var command: Char? = null
        var current = SvgPoint(0.0, 0.0)
        var subPathStart = current
        var startsNewSubPath = true
        var previousCommand: Char? = null
        var lastCubicControl: SvgPoint? = null
        var lastQuadraticControl: SvgPoint? = null
        val segments = mutableListOf<SvgSegment>()
        val unsupported = mutableSetOf<Char>()

        fun hasNumber(): Boolean = index < tokens.size && tokens[index].toDoubleOrNull() != null
        fun remainingNumbers(): Int {
            var count = 0
            var cursor = index
            while (cursor < tokens.size && tokens[cursor].toDoubleOrNull() != null) {
                count += 1
                cursor += 1
            }
            return count
        }
        fun number(): Double = tokens[index++].toDouble()
        fun nextCommandOrNull(): Char? {
            if (index >= tokens.size) return null
            val token = tokens[index]
            return if (token.length == 1 && token[0].isLetter()) token[0] else null
        }
        fun resetControls() {
            lastCubicControl = null
            lastQuadraticControl = null
        }
        fun addLine(next: SvgPoint) {
            segments += SvgSegment(
                start = transform.map(current),
                end = transform.map(next),
                continuesFromPrevious = !startsNewSubPath,
            )
            current = next
            startsNewSubPath = false
            resetControls()
        }
        fun addFlattened(points: List<SvgPoint>) {
            if (points.size < 2) return
            for (i in 0 until points.lastIndex) {
                segments += SvgSegment(
                    start = transform.map(points[i]),
                    end = transform.map(points[i + 1]),
                    continuesFromPrevious = if (i == 0) !startsNewSubPath else true,
                )
            }
            current = points.last()
            startsNewSubPath = false
        }

        while (index < tokens.size) {
            nextCommandOrNull()?.let {
                command = it
                index += 1
            }
            val cmd = command ?: break
            val relative = cmd.isLowerCase()
            when (cmd.uppercaseChar()) {
                'M' -> {
                    if (remainingNumbers() < 2) break
                    val first = point(number(), number(), current, relative)
                    current = first
                    subPathStart = first
                    startsNewSubPath = true
                    resetControls()
                    while (remainingNumbers() >= 2) {
                        addLine(point(number(), number(), current, relative))
                    }
                    previousCommand = 'M'
                }
                'L' -> {
                    while (remainingNumbers() >= 2) {
                        addLine(point(number(), number(), current, relative))
                    }
                    previousCommand = 'L'
                }
                'H' -> {
                    while (hasNumber()) {
                        val x = number()
                        addLine(current.copy(x = if (relative) current.x + x else x))
                    }
                    previousCommand = 'H'
                }
                'V' -> {
                    while (hasNumber()) {
                        val y = number()
                        addLine(current.copy(y = if (relative) current.y + y else y))
                    }
                    previousCommand = 'V'
                }
                'C' -> {
                    while (remainingNumbers() >= 6) {
                        val control1 = point(number(), number(), current, relative)
                        val control2 = point(number(), number(), current, relative)
                        val end = point(number(), number(), current, relative)
                        addFlattened(flattenCubic(current, control1, control2, end))
                        lastCubicControl = control2
                        lastQuadraticControl = null
                        previousCommand = 'C'
                    }
                }
                'S' -> {
                    while (remainingNumbers() >= 4) {
                        val control1 = if (previousCommand == 'C' || previousCommand == 'S') {
                            lastCubicControl?.reflectAround(current) ?: current
                        } else {
                            current
                        }
                        val control2 = point(number(), number(), current, relative)
                        val end = point(number(), number(), current, relative)
                        addFlattened(flattenCubic(current, control1, control2, end))
                        lastCubicControl = control2
                        lastQuadraticControl = null
                        previousCommand = 'S'
                    }
                }
                'Q' -> {
                    while (remainingNumbers() >= 4) {
                        val control = point(number(), number(), current, relative)
                        val end = point(number(), number(), current, relative)
                        addFlattened(flattenQuadratic(current, control, end))
                        lastQuadraticControl = control
                        lastCubicControl = null
                        previousCommand = 'Q'
                    }
                }
                'T' -> {
                    while (remainingNumbers() >= 2) {
                        val control = if (previousCommand == 'Q' || previousCommand == 'T') {
                            lastQuadraticControl?.reflectAround(current) ?: current
                        } else {
                            current
                        }
                        val end = point(number(), number(), current, relative)
                        addFlattened(flattenQuadratic(current, control, end))
                        lastQuadraticControl = control
                        lastCubicControl = null
                        previousCommand = 'T'
                    }
                }
                'A' -> {
                    while (remainingNumbers() >= 7) {
                        val rx = number()
                        val ry = number()
                        val xAxisRotation = number()
                        val largeArc = number().roundToInt() != 0
                        val sweep = number().roundToInt() != 0
                        val end = point(number(), number(), current, relative)
                        addFlattened(flattenArc(current, rx, ry, xAxisRotation, largeArc, sweep, end))
                        resetControls()
                        previousCommand = 'A'
                    }
                }
                'Z' -> {
                    if (current != subPathStart) {
                        segments += SvgSegment(
                            start = transform.map(current),
                            end = transform.map(subPathStart),
                            continuesFromPrevious = true,
                        )
                        current = subPathStart
                    }
                    startsNewSubPath = true
                    command = null
                    resetControls()
                    previousCommand = 'Z'
                }
                else -> {
                    unsupported += cmd.uppercaseChar()
                    while (index < tokens.size && nextCommandOrNull() == null) {
                        index += 1
                    }
                    resetControls()
                    previousCommand = cmd.uppercaseChar()
                }
            }
        }

        return if (segments.isEmpty() && unsupported.isEmpty()) null else ParsedPath(segments, unsupported)
    }

    private fun tokenizePath(data: String): List<String> {
        val tokens = mutableListOf<String>()
        var i = 0
        while (i < data.length) {
            val ch = data[i]
            when {
                ch.isWhitespace() || ch == ',' -> i += 1
                ch.isLetter() -> {
                    tokens += ch.toString()
                    i += 1
                }
                else -> {
                    val start = i
                    i += 1
                    while (i < data.length) {
                        val c = data[i]
                        val previous = data[i - 1]
                        val signStartsNumber = (c == '-' || c == '+') && previous != 'e' && previous != 'E'
                        if (c.isWhitespace() || c == ',' || c.isLetter() || signStartsNumber) break
                        i += 1
                    }
                    tokens += data.substring(start, i)
                }
            }
        }
        return tokens
    }

    private fun flattenCubic(p0: SvgPoint, p1: SvgPoint, p2: SvgPoint, p3: SvgPoint): List<SvgPoint> {
        val out = mutableListOf(p0)
        flattenCubicInto(p0, p1, p2, p3, depth = 0, out)
        return out
    }

    private fun flattenCubicInto(
        p0: SvgPoint,
        p1: SvgPoint,
        p2: SvgPoint,
        p3: SvgPoint,
        depth: Int,
        out: MutableList<SvgPoint>,
    ) {
        if (depth >= MaxCurveDepth || cubicFlatness(p0, p1, p2, p3) <= CurveFlatness) {
            out += p3
            return
        }
        val p01 = p0.mid(p1)
        val p12 = p1.mid(p2)
        val p23 = p2.mid(p3)
        val p012 = p01.mid(p12)
        val p123 = p12.mid(p23)
        val p0123 = p012.mid(p123)
        flattenCubicInto(p0, p01, p012, p0123, depth + 1, out)
        flattenCubicInto(p0123, p123, p23, p3, depth + 1, out)
    }

    private fun flattenQuadratic(p0: SvgPoint, p1: SvgPoint, p2: SvgPoint): List<SvgPoint> {
        val cubic1 = SvgPoint(
            x = p0.x + (2.0 / 3.0) * (p1.x - p0.x),
            y = p0.y + (2.0 / 3.0) * (p1.y - p0.y),
        )
        val cubic2 = SvgPoint(
            x = p2.x + (2.0 / 3.0) * (p1.x - p2.x),
            y = p2.y + (2.0 / 3.0) * (p1.y - p2.y),
        )
        return flattenCubic(p0, cubic1, cubic2, p2)
    }

    private fun flattenArc(
        p0: SvgPoint,
        rxInput: Double,
        ryInput: Double,
        xAxisRotation: Double,
        largeArc: Boolean,
        sweep: Boolean,
        p1: SvgPoint,
    ): List<SvgPoint> {
        var rx = abs(rxInput)
        var ry = abs(ryInput)
        if (p0 == p1) return listOf(p0, p1)
        if (rx <= 0.000001 || ry <= 0.000001) return listOf(p0, p1)

        val phi = xAxisRotation / 180.0 * PI
        val cosPhi = cos(phi)
        val sinPhi = sin(phi)
        val dx = (p0.x - p1.x) / 2.0
        val dy = (p0.y - p1.y) / 2.0
        val x1p = cosPhi * dx + sinPhi * dy
        val y1p = -sinPhi * dx + cosPhi * dy

        val radiiScale = x1p * x1p / (rx * rx) + y1p * y1p / (ry * ry)
        if (radiiScale > 1.0) {
            val scale = sqrt(radiiScale)
            rx *= scale
            ry *= scale
        }

        val rx2 = rx * rx
        val ry2 = ry * ry
        val x1p2 = x1p * x1p
        val y1p2 = y1p * y1p
        val denominator = rx2 * y1p2 + ry2 * x1p2
        val centerScale = if (denominator <= 0.000001) {
            0.0
        } else {
            val numerator = max(0.0, rx2 * ry2 - rx2 * y1p2 - ry2 * x1p2)
            val sign = if (largeArc == sweep) -1.0 else 1.0
            sign * sqrt(numerator / denominator)
        }

        val cxp = centerScale * rx * y1p / ry
        val cyp = centerScale * -ry * x1p / rx
        val center = SvgPoint(
            x = cosPhi * cxp - sinPhi * cyp + (p0.x + p1.x) / 2.0,
            y = sinPhi * cxp + cosPhi * cyp + (p0.y + p1.y) / 2.0,
        )

        val startVector = SvgPoint((x1p - cxp) / rx, (y1p - cyp) / ry)
        val endVector = SvgPoint((-x1p - cxp) / rx, (-y1p - cyp) / ry)
        val startAngle = angleBetween(SvgPoint(1.0, 0.0), startVector)
        var sweepAngle = angleBetween(startVector, endVector)
        if (!sweep && sweepAngle > 0.0) {
            sweepAngle -= 2.0 * PI
        } else if (sweep && sweepAngle < 0.0) {
            sweepAngle += 2.0 * PI
        }

        val byAngle = ceil(abs(sweepAngle) / (PI / 18.0)).toInt()
        val byLength = ceil(abs(sweepAngle) * max(rx, ry) / 3.0).toInt()
        val steps = max(4, max(byAngle, byLength)).coerceAtMost(180)
        val points = mutableListOf(p0)
        for (i in 1..steps) {
            val theta = startAngle + sweepAngle * i / steps
            val cosTheta = cos(theta)
            val sinTheta = sin(theta)
            points += SvgPoint(
                x = center.x + cosPhi * rx * cosTheta - sinPhi * ry * sinTheta,
                y = center.y + sinPhi * rx * cosTheta + cosPhi * ry * sinTheta,
            )
        }
        points[points.lastIndex] = p1
        return points
    }

    private fun angleBetween(from: SvgPoint, to: SvgPoint): Double {
        val cross = from.x * to.y - from.y * to.x
        val dot = from.x * to.x + from.y * to.y
        return atan2(cross, dot)
    }

    private fun cubicFlatness(p0: SvgPoint, p1: SvgPoint, p2: SvgPoint, p3: SvgPoint): Double {
        return max(distanceToLine(p1, p0, p3), distanceToLine(p2, p0, p3))
    }

    private fun distanceToLine(point: SvgPoint, start: SvgPoint, end: SvgPoint): Double {
        val dx = end.x - start.x
        val dy = end.y - start.y
        val length = hypot(dx, dy)
        if (length <= 0.000001) return hypot(point.x - start.x, point.y - start.y)
        return abs(dy * point.x - dx * point.y + end.x * start.y - end.y * start.x) / length
    }

    private fun parseTransform(value: String): SvgMatrix {
        if (value.isBlank()) return SvgMatrix.Identity
        var matrix = SvgMatrix.Identity
        transformRegex.findAll(value).forEach { match ->
            val name = match.groupValues[1].lowercase(Locale.US)
            val args = parseNumberList(match.groupValues[2])
            val next = when (name) {
                "matrix" -> if (args.size >= 6) SvgMatrix(args[0], args[1], args[2], args[3], args[4], args[5]) else null
                "translate" -> if (args.isNotEmpty()) SvgMatrix.translation(args[0], args.getOrElse(1) { 0.0 }) else null
                "scale" -> if (args.isNotEmpty()) SvgMatrix.scale(args[0], args.getOrElse(1) { args[0] }) else null
                "rotate" -> when {
                    args.size >= 3 -> {
                        val rotate = SvgMatrix.rotation(args[0])
                        SvgMatrix.translation(args[1], args[2])
                            .multiply(rotate)
                            .multiply(SvgMatrix.translation(-args[1], -args[2]))
                    }
                    args.isNotEmpty() -> SvgMatrix.rotation(args[0])
                    else -> null
                }
                "skewx" -> if (args.isNotEmpty()) SvgMatrix.skewX(args[0]) else null
                "skewy" -> if (args.isNotEmpty()) SvgMatrix.skewY(args[0]) else null
                else -> null
            }
            if (next != null) {
                matrix = matrix.multiply(next)
            }
        }
        return matrix
    }

    private fun parseNumberList(value: String): List<Double> {
        return numberRegex.findAll(value).mapNotNull { it.value.toDoubleOrNull() }.toList()
    }

    private fun point(x: Double, y: Double, current: SvgPoint, relative: Boolean): SvgPoint {
        return if (relative) SvgPoint(current.x + x, current.y + y) else SvgPoint(x, y)
    }

    private fun SvgPoint.toMachine(minX: Double, maxY: Double, scale: Double): SvgPoint {
        return SvgPoint(
            x = (x - minX) * scale,
            y = (maxY - y) * scale,
        )
    }

    private fun Element.attr(name: String): String = getAttribute(name).orEmpty()

    private fun Element.doubleAttr(name: String): Double? {
        return numberRegex.find(attr(name)).takeIf { it != null }?.value?.toDoubleOrNull()
    }

    private fun fmt(value: Double): String = String.format(Locale.US, "%.3f", value.roundTo(0.001))

    private fun Double.roundTo(step: Double): Double = (this / step).roundToInt() * step
}

private data class SvgPoint(val x: Double, val y: Double) {
    fun mid(other: SvgPoint): SvgPoint = SvgPoint((x + other.x) / 2.0, (y + other.y) / 2.0)

    fun reflectAround(center: SvgPoint): SvgPoint = SvgPoint(
        x = center.x * 2.0 - x,
        y = center.y * 2.0 - y,
    )
}

private data class SvgSegment(
    val start: SvgPoint,
    val end: SvgPoint,
    val continuesFromPrevious: Boolean,
)

private data class ParsedPath(
    val segments: List<SvgSegment>,
    val unsupportedCommands: Set<Char>,
    val layer: SvgLayerKey = SvgLayerKey.Default,
)

private data class SvgLayerKey(
    val id: String,
    val label: String,
) {
    companion object {
        val Default = SvgLayerKey("#000000", "#000000")
    }
}

private data class SvgLayerProfile(
    val label: String,
    val target: SvgLayerTarget,
    val power: Int,
    val feedRate: Int,
)

private data class SvgOutputLayer(
    val profile: SvgLayerProfile,
    val paths: List<ParsedPath>,
)

private data class SvgStyle(
    val stroke: String? = null,
    val fill: String? = "#000000",
    val color: String = "#000000",
    val display: String = "inline",
    val visibility: String = "visible",
    val opacity: String = "1",
    val strokeOpacity: String = "1",
    val fillOpacity: String = "1",
) {
    companion object {
        val Default = SvgStyle()
    }
}

private data class SvgMatrix(
    val a: Double,
    val b: Double,
    val c: Double,
    val d: Double,
    val e: Double,
    val f: Double,
) {
    fun map(point: SvgPoint): SvgPoint {
        return SvgPoint(
            x = a * point.x + c * point.y + e,
            y = b * point.x + d * point.y + f,
        )
    }

    fun multiply(other: SvgMatrix): SvgMatrix {
        return SvgMatrix(
            a = a * other.a + c * other.b,
            b = b * other.a + d * other.b,
            c = a * other.c + c * other.d,
            d = b * other.c + d * other.d,
            e = a * other.e + c * other.f + e,
            f = b * other.e + d * other.f + f,
        )
    }

    companion object {
        val Identity = SvgMatrix(1.0, 0.0, 0.0, 1.0, 0.0, 0.0)

        fun translation(x: Double, y: Double): SvgMatrix = SvgMatrix(1.0, 0.0, 0.0, 1.0, x, y)

        fun scale(x: Double, y: Double): SvgMatrix = SvgMatrix(x, 0.0, 0.0, y, 0.0, 0.0)

        fun rotation(degrees: Double): SvgMatrix {
            val radians = degrees / 180.0 * PI
            val cos = cos(radians)
            val sin = sin(radians)
            return SvgMatrix(cos, sin, -sin, cos, 0.0, 0.0)
        }

        fun skewX(degrees: Double): SvgMatrix = SvgMatrix(1.0, 0.0, tan(degrees / 180.0 * PI), 1.0, 0.0, 0.0)

        fun skewY(degrees: Double): SvgMatrix = SvgMatrix(1.0, tan(degrees / 180.0 * PI), 0.0, 1.0, 0.0, 0.0)
    }
}
